// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/7de6c3dd94feaeb21f20054b9f30d5dabc5efabd/jwt-decode/jwt-decode.d.ts
declare namespace JwtDecode {
    interface JwtDecodeStatic {
        (token: string): any;
    }
}

declare module 'jwt-decode' {
    var jwtDecode: JwtDecode.JwtDecodeStatic;
    export = jwtDecode;
}
